# lipsync_integration.py - Integration module for actual lipsync functionality

import os
import time
import subprocess
from pathlib import Path
from colorama import Fore, Style, init

# Initialize colorama
init(autoreset=True)

# Set project directory (one folder above scripts)
PROJECT_DIR = os.path.dirname(os.path.dirname(__file__))

def generate_lipsync_video(audio_file_path: str, output_filename: str = None) -> tuple[bool, str]:
    """
    Generate lipsync video using the existing lipsync.py module.
    
    Args:
        audio_file_path: Path to the audio file generated by TTS
        output_filename: Optional custom output filename
    
    Returns:
        tuple: (success: bool, video_path: str)
    """
    try:
        print(f"{Fore.MAGENTA}[LIPSYNC] Starting lipsync generation...{Style.RESET_ALL}")
        print(f"{Fore.BLUE}[LIPSYNC] Audio file: {audio_file_path}{Style.RESET_ALL}")
        
        if not os.path.exists(audio_file_path):
            print(f"{Fore.RED}[LIPSYNC] Audio file not found: {audio_file_path}{Style.RESET_ALL}")
            return False, None
        
        # Import the existing lipsync module
        try:
            from lipsync import LipSyncGenerator
        except ImportError as e:
            print(f"{Fore.RED}[LIPSYNC] Failed to import lipsync module: {e}{Style.RESET_ALL}")
            print(f"{Fore.YELLOW}[LIPSYNC] Make sure lipsync.py is in the scripts directory{Style.RESET_ALL}")
            return False, None
        
        # Setup output filename
        if output_filename is None:
            timestamp = int(time.time())
            output_filename = f"darwin_lipsync_{timestamp}.mp4"
        
        # Ensure output directory exists
        output_dir = os.path.join(PROJECT_DIR, "tempstream")
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, output_filename)
        
        # Setup paths for lipsync generation
        word_clips_dir = os.path.join(PROJECT_DIR, "word_clips", "focus_in")
        ffmpeg_bin_path = r"C:\ffmpeg\bin"  # Update this path as needed
        
        # Check if word clips directory exists
        if not os.path.exists(word_clips_dir):
            print(f"{Fore.RED}[LIPSYNC] Word clips directory not found: {word_clips_dir}{Style.RESET_ALL}")
            return False, None
        
        # Check if FFmpeg is available
        if not os.path.exists(ffmpeg_bin_path):
            print(f"{Fore.RED}[LIPSYNC] FFmpeg not found at: {ffmpeg_bin_path}{Style.RESET_ALL}")
            return False, None
        
        print(f"{Fore.CYAN}[LIPSYNC] Using word clips from: {word_clips_dir}{Style.RESET_ALL}")
        print(f"{Fore.CYAN}[LIPSYNC] Output will be saved to: {output_path}{Style.RESET_ALL}")
        
        # Initialize the lipsync generator
        lipsync_generator = LipSyncGenerator(
            video_clips_dir=word_clips_dir,
            ffmpeg_path=ffmpeg_bin_path,
            model_size="tiny"  # Use tiny model for faster processing
        )
        
        # Generate the lipsync video
        start_time = time.time()
        success = lipsync_generator.generate_lipsync_video(
            audio_file=audio_file_path,
            output_file=output_path
        )
        
        generation_time = time.time() - start_time
        
        if success and os.path.exists(output_path):
            print(f"{Fore.GREEN}[LIPSYNC] Lipsync video generated successfully in {generation_time:.2f}s{Style.RESET_ALL}")
            print(f"{Fore.GREEN}[LIPSYNC] Output file: {output_path}{Style.RESET_ALL}")
            return True, output_path
        else:
            print(f"{Fore.RED}[LIPSYNC] Lipsync generation failed after {generation_time:.2f}s{Style.RESET_ALL}")
            return False, None
            
    except Exception as e:
        print(f"{Fore.RED}[LIPSYNC] Error during lipsync generation: {e}{Style.RESET_ALL}")
        import traceback
        traceback.print_exc()
        return False, None


def test_lipsync_system() -> bool:
    """
    Test the lipsync system with a sample audio file.
    
    Returns:
        bool: True if test passes, False otherwise
    """
    try:
        print(f"{Fore.CYAN}[LIPSYNC_TEST] Testing lipsync system...{Style.RESET_ALL}")
        
        # Check if lipsync module can be imported
        try:
            from lipsync import LipSyncGenerator
            print(f"{Fore.GREEN}[LIPSYNC_TEST] Lipsync module imported successfully{Style.RESET_ALL}")
        except ImportError as e:
            print(f"{Fore.RED}[LIPSYNC_TEST] Failed to import lipsync module: {e}{Style.RESET_ALL}")
            return False
        
        # Check required directories
        word_clips_dir = os.path.join(PROJECT_DIR, "word_clips", "focus_in")
        ffmpeg_bin_path = r"C:\ffmpeg\bin"
        
        if not os.path.exists(word_clips_dir):
            print(f"{Fore.RED}[LIPSYNC_TEST] Word clips directory not found: {word_clips_dir}{Style.RESET_ALL}")
            return False
        
        if not os.path.exists(ffmpeg_bin_path):
            print(f"{Fore.RED}[LIPSYNC_TEST] FFmpeg not found at: {ffmpeg_bin_path}{Style.RESET_ALL}")
            return False
        
        # Count available word clips
        word_clips = [f for f in os.listdir(word_clips_dir) if f.endswith(('.mp4', '.avi', '.mov', '.mkv'))]
        print(f"{Fore.GREEN}[LIPSYNC_TEST] Found {len(word_clips)} word clips{Style.RESET_ALL}")
        
        if len(word_clips) == 0:
            print(f"{Fore.RED}[LIPSYNC_TEST] No word clips found in directory{Style.RESET_ALL}")
            return False
        
        # Try to initialize the lipsync generator
        try:
            lipsync_generator = LipSyncGenerator(
                video_clips_dir=word_clips_dir,
                ffmpeg_path=ffmpeg_bin_path,
                model_size="tiny"
            )
            print(f"{Fore.GREEN}[LIPSYNC_TEST] LipSyncGenerator initialized successfully{Style.RESET_ALL}")
        except Exception as e:
            print(f"{Fore.RED}[LIPSYNC_TEST] Failed to initialize LipSyncGenerator: {e}{Style.RESET_ALL}")
            return False
        
        print(f"{Fore.GREEN}[LIPSYNC_TEST] All lipsync system components verified successfully{Style.RESET_ALL}")
        return True
        
    except Exception as e:
        print(f"{Fore.RED}[LIPSYNC_TEST] Lipsync system test failed: {e}{Style.RESET_ALL}")
        return False


# Enhanced test function that replaces the simple one in node_video_system.py
def generate_lipsync_with_integration(text: str, output_filename: str = None) -> tuple[bool, str]:
    """
    Enhanced lipsync function that integrates with the actual lipsync system.
    This replaces the test_lipsync_function in node_video_system.py
    
    Args:
        text: Text to convert to lipsync video
        output_filename: Optional custom output filename
    
    Returns:
        tuple: (is_ready: bool, file_path: str)
    """
    try:
        print(f"{Fore.MAGENTA}[LIPSYNC_ENHANCED] Starting enhanced lipsync generation...{Style.RESET_ALL}")
        print(f"{Fore.BLUE}[LIPSYNC_ENHANCED] Text: {text[:50]}{'...' if len(text) > 50 else ''}{Style.RESET_ALL}")
        
        # Step 1: Generate TTS audio
        from enhanced_tts_piper import generate_complete_audio
        
        audio_timestamp = int(time.time())
        audio_filename = f"lipsync_audio_{audio_timestamp}"
        audio_path = generate_complete_audio(text, audio_filename)
        
        if not audio_path or not os.path.exists(audio_path):
            print(f"{Fore.RED}[LIPSYNC_ENHANCED] Failed to generate TTS audio{Style.RESET_ALL}")
            return False, None
        
        print(f"{Fore.GREEN}[LIPSYNC_ENHANCED] TTS audio generated: {audio_path}{Style.RESET_ALL}")
        
        # Step 2: Generate lipsync video
        success, video_path = generate_lipsync_video(audio_path, output_filename)
        
        # Step 3: Cleanup temporary audio file (optional)
        try:
            os.remove(audio_path)
            print(f"{Fore.CYAN}[LIPSYNC_ENHANCED] Cleaned up temporary audio file{Style.RESET_ALL}")
        except:
            pass  # Ignore cleanup errors
        
        if success:
            print(f"{Fore.GREEN}[LIPSYNC_ENHANCED] Enhanced lipsync generation completed successfully{Style.RESET_ALL}")
            return True, video_path
        else:
            print(f"{Fore.RED}[LIPSYNC_ENHANCED] Enhanced lipsync generation failed{Style.RESET_ALL}")
            return False, None
            
    except Exception as e:
        print(f"{Fore.RED}[LIPSYNC_ENHANCED] Error in enhanced lipsync generation: {e}{Style.RESET_ALL}")
        import traceback
        traceback.print_exc()
        return False, None


def setup_lipsync_environment():
    """
    Setup and verify the lipsync environment.
    This should be called during application startup.
    
    Returns:
        bool: True if environment is ready, False otherwise
    """
    print(f"{Fore.CYAN}[LIPSYNC_SETUP] Setting up lipsync environment...{Style.RESET_ALL}")
    
    # Test the lipsync system
    if not test_lipsync_system():
        print(f"{Fore.RED}[LIPSYNC_SETUP] Lipsync system test failed{Style.RESET_ALL}")
        return False
    
    # Ensure output directory exists
    output_dir = os.path.join(PROJECT_DIR, "tempstream")
    os.makedirs(output_dir, exist_ok=True)
    print(f"{Fore.GREEN}[LIPSYNC_SETUP] Output directory ready: {output_dir}{Style.RESET_ALL}")
    
    print(f"{Fore.GREEN}[LIPSYNC_SETUP] Lipsync environment setup completed successfully{Style.RESET_ALL}")
    return True


if __name__ == "__main__":
    print(f"{Fore.GREEN}{'=' * 60}")
    print(f"{Fore.YELLOW}Lipsync Integration Module Test")
    print(f"{Fore.GREEN}{'=' * 60}{Style.RESET_ALL}")
    
    # Test the setup
    if setup_lipsync_environment():
        print(f"\n{Fore.GREEN}Lipsync environment is ready!{Style.RESET_ALL}")
        
        # Interactive test
        test_choice = input(f"\n{Fore.CYAN}Test lipsync generation? (y/n): {Style.RESET_ALL}")
        if test_choice.lower() == 'y':
            test_text = input(f"{Fore.CYAN}Enter text for lipsync generation: {Style.RESET_ALL}")
            if test_text.strip():
                print(f"\n{Fore.YELLOW}Starting lipsync generation test...{Style.RESET_ALL}")
                success, video_path = generate_lipsync_with_integration(test_text)
                
                if success:
                    print(f"{Fore.GREEN}✅ Lipsync test successful!{Style.RESET_ALL}")
                    print(f"{Fore.GREEN}Video saved to: {video_path}{Style.RESET_ALL}")
                else:
                    print(f"{Fore.RED}❌ Lipsync test failed{Style.RESET_ALL}")
            else:
                print(f"{Fore.YELLOW}No text provided, skipping test{Style.RESET_ALL}")
    else:
        print(f"\n{Fore.RED}❌ Lipsync environment setup failed{Style.RESET_ALL}")
        print(f"{Fore.YELLOW}Please check the following:{Style.RESET_ALL}")
        print(f"  - lipsync.py is in the scripts directory")
        print(f"  - word_clips/focus_in directory exists with video clips")
        print(f"  - FFmpeg is installed and path is correct")
        print(f"  - All required Python dependencies are installed")